### ISSUE TITLE
Create To-Do (route)

### ISSUE THREAD

**Issue by zeldacodes** [Capstone-Project-Team-ToDomagotchi/todomagotchi#14]

**Comment by zeldacodes** [comment]
- [ ] updated API file:
index.js
- [ ] created API file:
todo.js
- [ ] updated the name of the app via the navbar:
Navbar.js
